name: Run tests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run-minitest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependancies
        run: |
          apt install bundler
      - name: Set up Ruby
        run: |
          bundle install
      - name: Run tests
        run: |
          bash tests/run.sh
